<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KRUPA" failures="4" tests="13" name="User API Tests" time="26.75" errors="0" timestamp="2025-10-29T13:36:02 IST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="2.793"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="9.131"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="2.11"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.085"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.152"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.057"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.056"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.086"/>
  <testcase classname="api.test.DDTests" name="testReadUserByName" time="1.045">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testReadUserByName(DDTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testReadUserByName -->
  <testcase classname="api.test.DDTests" name="testReadUserByName" time="1.034">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testReadUserByName(DDTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testReadUserByName -->
  <testcase classname="api.test.DDTests" name="testReadUserByName" time="1.051">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testReadUserByName(DDTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testReadUserByName -->
  <testcase classname="api.test.DDTests" name="testReadUserByName" time="1.031">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testReadUserByName(DDTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testReadUserByName -->
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="0.0">
    <skipped/>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- User API Tests -->
